import Card from "../ui/Card";
import Badge from "../ui/Badge";
import { exportCompliancePDF } from "../../utils/exportPDF";

function ResultCard({ result, loading }) {
  if (loading) {
    return (
      <Card>
        <h2 className="text-2xl font-bold mb-6">
          🤖 AI Compliance Engine
        </h2>

        <div className="flex justify-center mb-6">
          <div className="animate-spin w-12 h-12 border-4 border-black border-t-transparent rounded-full"></div>
        </div>

        <div className="space-y-4 text-lg">
          <p>🔍 Analyzing Wallet Address...</p>
          <p>🛡 Checking AML & Sanctions Lists...</p>
          <p>🌍 Verifying Investor Jurisdiction...</p>
          <p>📊 Calculating Compliance Risk...</p>
          <p>🤖 Generating AI Compliance Report...</p>
        </div>
      </Card>
    );
  }

  if (!result) {
    return (
      <Card>
        <h2 className="text-2xl font-bold mb-6">
          AI Compliance Assessment
        </h2>

        <div className="text-center py-16">
          <div className="text-6xl mb-4">🛡</div>

          <h3 className="text-xl font-bold mb-2">
            No Compliance Report
          </h3>

          <p className="text-gray-500">
            Run your first compliance check to generate an AI assessment.
          </p>
        </div>
      </Card>
    );
  }

  return (
    <Card>
      {/* Header */}

      <div className="flex justify-between items-center mb-8">
        <h2 className="text-3xl font-bold">
          AI Compliance Assessment
        </h2>

        <Badge status={result.status} />
      </div>

      {/* Details */}

      <div className="space-y-5">

        <div className="flex justify-between border-b pb-3">
          <span className="font-semibold">
            Risk Score
          </span>

          <span className="font-bold text-lg">
            {result.risk}/100
          </span>
        </div>

        <div className="flex justify-between border-b pb-3">
          <span className="font-semibold">
            Compliance ID
          </span>

          <span>{result.complianceId}</span>
        </div>

        <div className="flex justify-between border-b pb-3">
          <span className="font-semibold">
            Casper Hash
          </span>

          <span className="font-mono text-xs break-all text-right">
            {result.blockchainHash}
          </span>
        </div>

        <div className="flex justify-between border-b pb-3">
          <span className="font-semibold">
            Recommendation
          </span>

          <span
            className={`font-bold ${
              result.status === "PASS"
                ? "text-green-600"
                : "text-red-600"
            }`}
          >
            {result.status === "PASS"
              ? "Approved"
              : "Manual Review Required"}
          </span>
        </div>

      </div>

      {/* AI Assessment */}

      <div className="mt-8">

        <h3 className="font-bold text-lg mb-3">
          🤖 AI Assessment
        </h3>

        <div className="bg-gray-100 border-2 border-black rounded-md p-4 leading-8 text-gray-700">
          {result.explanation}
        </div>

      </div>

      {/* Download PDF */}

      <button
        onClick={() => exportCompliancePDF(result)}
        className="
          mt-8
          w-full
          bg-black
          text-white
          border-2
          border-black
          py-3
          font-semibold
          hover:bg-white
          hover:text-black
          transition
        "
      >
        📄 Download Compliance Report
      </button>

      {/* Footer */}

      <p className="text-center text-xs text-gray-500 mt-5">
        Generated by AI Compliance Guardian • Powered by Gemini AI & Casper Network
      </p>
    </Card>
  );
}

export default ResultCard;